---
steps:
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker pull gcr.io/$PROJECT_ID/[IMAGE_NAME]:latest || exit 0']
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/[IMAGE_NAME]:latest',
      '--cache-from', 'gcr.io/$PROJECT_ID/[IMAGE_NAME]:latest',
      '.'
    ]
images: ['gcr.io/$PROJECT_ID/[IMAGE_NAME]:latest']
