# Use correct image for Apache Beam version
FROM apache/beam_python3.7_sdk:2.35.0

# Install TFDV on top 
RUN pip install tensorflow-data-validation==1.6.0

# Check version compatibilities here
# https://www.tensorflow.org/tfx/data_validation/install#compatible_versions
